# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2018-02-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('nutrition_value', models.PositiveIntegerField(blank=True, default=0, verbose_name='Пищевая ценность')),
                ('value', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.CharField(max_length=256, verbose_name='Путь к изображению')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Dishes', verbose_name='Блюдо')),
            ],
        ),
    ]
