# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2018-02-16 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.CharField(max_length=512, verbose_name='Путь к изображению'),
        ),
    ]
