# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-16 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180216_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
