# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180216_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Путь к изображению'),
        ),
    ]
